---
- name: base system configurations for linux servers
  hosts: prod
  become: true
  gather_facts: false
  tasks:
  - name: create admin user
    user:
      name: admin
      uid: 5001
      state: present
  - name: remove dojo user
    user: 
      name: dojo
      state: absent
  - name: install tree
    package: 
      name: tree
      state: present
  - name: install ntp
    package: 
      name: ntp
      state: present
  - name: start ntp service
    service:
      name: ntpd
      state: started

- name: configuring app server
  hosts: app
  gather_facts: false
  become: true
  tasks:
  - name: create deploy user
    user:
      name: deploy
      uid: 503
      state: present
  - name: install git
    package:
      name: git
      state: present
...
